version: "3.7"
services:
  backend:
    image: <image goes here>
    environment:
      DB_HOST: dbs
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    depends_on:
      - dbs
    restart: always

  dbs:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
